on:
  workflow_call:
    inputs:
      solution-path:
        type: string
        description: 'The relative path to the .sln file (default: current directory)'
        required: false
        default: '.'
      solution-name:
        type: string
        description: 'The name of the solution file (e.g., MyApp.sln)'
        required: true

env:
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use

jobs:
  setup:
    name: Setup .NET Core
    runs-on: ubuntu-latest
    outputs:
      solution-path: ${{ inputs.solution-path }}
      solution-name: ${{ inputs.solution-name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install dependencies
        run: dotnet restore ${{ needs.setup.outputs.solution-path }}/${{ needs.setup.outputs.solution-name }}

      - name: Run build
        run: dotnet build ${{ needs.setup.outputs.solution-path }}/${{ needs.setup.outputs.solution-name }} --configuration Release

  analysis:
    name: Analysis
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Run code analysis report
      run: dotnet format ${{ needs.setup.outputs.solution-path }}/${{ needs.setup.outputs.solution-name }} --verify-no-changes --verbosity diagnostic --report ./analysis

    - name: Upload code analysis report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Code Analysis Report
        path: ${{ needs.setup.outputs.solution-path }}/analysis/format-report.json
        retention-days: 1
