on:
  workflow_call:
    inputs:
      solution-path:
        type: string
        description: 'The relative path to the .sln file (default: current directory)'
        required: false
        default: '.'
      solution-name:
        type: string
        description: 'The name of the solution file (e.g., MyApp.sln)'
        required: true
      self-hosted-labels:
        type: string
        description: 'Comma-separated list of self-hosted runner labels'
        required: true
        default: '[ ubuntu-latest ]'

env:
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use
  FULL_SOLUTION_PATH: ${{ inputs.solution-path }}/${{ inputs.solution-name }}

jobs:
  analysis:
    name: Analysis
    runs-on: ${{ fromJson(inputs.self-hosted-labels) }}
    timeout-minutes: 5
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run code analysis report
        run: dotnet format ${{ ENV.FULL_SOLUTION_PATH }} --verify-no-changes --verbosity diagnostic --report ./analysis

      - name: Upload code analysis report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Code Analysis Report
          path: ${{ inputs.solution-path }}/analysis/format-report.json
          retention-days: 1
            
       # 📝 Comment on PR when blocked
      - name: Comment on PR if Analysis Fail
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: analysis
          recreate: true
          message: |
            ❌ The analysis failed. The PR has been marked as **Blocked: Analysis Fix Required**. Please fix the issues before pushing again.
