on:
  workflow_call:
    inputs:
      solution-path:
        type: string
        description: 'The relative path to the .sln file (default: current directory)'
        required: false
        default: '.'
      solution-name:
        type: string
        description: 'The name of the solution file (e.g., MyApp.sln)'
        required: true

env:
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use
  FULL_SOLUTION_PATH: ${{ inputs.solution-path }}/${{ inputs.solution-name }}

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'Blocked: Analysis Fix Required')"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run code analysis report
        run: dotnet format ${{ ENV.FULL_SOLUTION_PATH }} --verify-no-changes --verbosity diagnostic --report ./analysis

      - name: Upload code analysis report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Code Analysis Report
          path: ${{ inputs.solution-path }}/analysis/format-report.json
          retention-days: 1
          
      # 🛑 Add "Blocked: Fix Required" label if tests fail
      - name: Block PR if Analysis Fail
        if: failure() && github.event_name == 'pull_request'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels \
            -d '{"labels":["Blocked: Analysis Fix Required"]}'
            
       # 📝 Comment on PR when blocked
      - name: Comment on PR if Analysis Fail
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && failure()
        with:
          recreate: true
          message: |
            ❌ The analysis failed. The PR has been marked as **Blocked: Analysis Fix Required**. Please fix the issues before pushing again.
